steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t gcr.io/sns2ps-api-image-build-217d/sns2ps-api:$TAG_NAME .
      docker push gcr.io/sns2ps-api-image-build-217d/sns2ps-api:$TAG_NAME